### PR TITLE
added front end parts to the add photos section

### PR DESCRIPTION
**Pull request by sebslaman**

### CODE REVIEW

**Comment by DouglasSherk** [comment]
fixes #48

**Comment by sebslaman** [comment]
Updated pull request with:
  All photo potions on one page
  able to take photos on mobile
  able to add photos currently on devise
does not currently allow data storage and saving

**Comment by mhxu** [comment]
fixes (D/N edit: not) #17

**Comment by mhxu** [comment]
fixes #40

**Comment by DouglasSherk** [comment]
Please use branches for each issue. This pull request contains fixes for 3 different issues, but I don't want to merge in 2 of them. For now, I'm going to merge in only the schedules changes, but I'm going to have to do it manually because there's now 3 schedules.

**Comment by DouglasSherk** [comment]
This pull request is too jumbled at this point so I'm closing it. The photos code should go in its own pull request.

**Comment by DouglasSherk** [comment]
Oh, though it should be noted that I merged in 2/3 the changes proposed here. Only the photos code remains.

**Pull request closed without merging**
