### PR TITLE
Added Intelligent dropdowns

### LINKED ISSUE #35: Intelligent 'other' dropdowns (auto fill based on other values you have used before, a la Excel)

### PR DESCRIPTION
**Pull request by mhxu**
fixes #35

### CODE REVIEW

**Comment by mhxu** [comment]
The code has been updated.

**Comment by mhxu** [comment]
I don't how to test whether or not my code works for models that are more than 2 levels deep.(or whatever they are called)

**Comment by DouglasSherk** [comment]
You can't really test it right now. We'll have to just do code review and cross our fingers. Someone will likely have to come back to this.

**Comment by mhxu** [comment]
I accidentally squashed too much together.  It seems like you can't squash a merge.  I changed a few lines concerning the `modelCollection` and the  `$("div#modal-" + modelCollection)`

**Comment by mhxu** [comment]
Added some comments.

**Pull request merged**
